### ISSUE TITLE
DocC-GPT ate my code!

### ISSUE THREAD

**Issue by davidfekke** [gonzalonunez/docc-gpt#17]
I ran DocC-GPT on a swift package I have called Animal Years. It is a very simple class with two methods. After running DocC-GPT on my package, it did add documentation text comments to the class and and the first method, but it clipped off the end of my first method, and completely deleted my second method.

**Comment by gonzalonunez** [comment]
Hey @davidfekke! Is the package public by any chance? Would love to see the files. Looks like you ran out of tokens (see the warning in the `README.md`)

Some questions:

- What model did you run it with?
- What context length did you give it?
- Did you run it with `--skip-files false`?

I can definitely improve the heuristic with which it chooses to skip files, the logic is [here](https://github.com/gonzalonunez/docc-gpt/blob/d281b56a139b08e9a177213e235133b6a63e40ca/Sources/docc-gpt/DoccGPTRunner.swift#L88).

**Comment by gonzalonunez** [comment]
Right now, the prompt _and_ the original file need to fit inside of the context window together with enough tokens leftover for the entire original file to be returned _plus_ room for comments.

**Comment by gonzalonunez** [comment]
Also, you didn't permanently lose any code right?! 🙏

**Comment by davidfekke** [comment]
I keep all of my code in a git repo, so no, I did not lose any code.

My package is public.

[https://github.com/davidfekke/AnimalYears](https://github.com/davidfekke/AnimalYears)

**Comment by gonzalonunez** [comment]
@davidfekke what version of `docc-gpt` were you on? I just got the skip warning on version `0.3.1`:

```
⚠︎ Skipping Convert.swift due to number of tokens in prompt (4230). This can happen for a number of reasons:

	1. Make sure that the --context-length argument (4096) is appropriate for the model that
	you've chosen to use. Most models have a context length of 2048 tokens (except for the newest models,
	which support 4096).

	2. The token count of your prompt plus max_tokens cannot exceed the model's context length. The
	prompt for this file is using 4230 tokens, which leaves -134 tokens remaining.
```

Either way, I'm going to improve the logic here to make it a little bit more strict.

One thing you can do is use `gpt-4` if you have access to it, which has a context window of `8092`. And soon we'll have context windows of 32k tokens which will dramatically improve DoccGPT's ability to document that average Swift file.

This command would work for `AnimalYears`:
```
docc-gpt Sources/AnimalYears --model "gpt-4" --context-length 8,192 --key <key>
```

**Comment by davidfekke** [comment]
Thanks. I have access to GPT-4, so I will try again.

**Comment by gonzalonunez** [comment]
Great! Thanks for filing this, I'll tweak the heuristic for skipping files and close this once I do.
