### ISSUE TITLE
How to set Open AI key?

### ISSUE THREAD

**Issue by fifyrio** [gonzalonunez/docc-gpt#25]

**Comment by gonzalonunez** [comment]
Hi @fifyrio! You can set the API key by passing it as an option to the command:

```bash
mint run docc-gpt Sources/Ginny -k <your-openai-key>
```

See here for the code:

https://github.com/gonzalonunez/docc-gpt/blob/0a3eeb6aebfeff5dcafc302d0b2f2e53b6ad237e/Sources/docc-gpt/DoccGPT.swift#L40
